const $=s=>document.querySelector(s);
async function getJSON(u){const r=await fetch(u);if(!r.ok)throw new Error(u);return r.json()}
function setTheme(s){const c=s.colors||{},f=s.fonts||{};const r=document.documentElement.style;r.setProperty("--cream",c.cream||"#E6DDCF");r.setProperty("--mustard",c.mustard||"#DDB982");r.setProperty("--burgundy",c.burgundy||"#7A4C4D");r.setProperty("--white",c.warmWhite||"#F7F3ED");r.setProperty("--blue",c.blue||"#69A8DA");r.setProperty("--display",`"${f.display||"DM Serif Display"}"`);r.setProperty("--body",`"${f.body||"Libre Baskerville"}"`)}
function menu(){return `<div class="menu" id="menu"><div style="display:flex;justify-content:space-between"><span class="brand">The Studio by Petra</span><button class="close" onclick="toggleMenu()">×</button></div><nav><a href="/#home">Home</a><a href="/#about">About me</a><a href="/#projects">Projects</a><a href="/#contact">Contact</a></nav></div>`}
window.toggleMenu=()=>$("#menu").classList.toggle("open");
async function loadProjects(){const names=["freedom-the-label","musa-beer-on-tiktok"];return Promise.all(names.map(n=>getJSON(`/content/projects/${n}.json`)))}
async function home(){
 const [s,ps]=await Promise.all([getJSON("/content/site.json"),loadProjects()]);setTheme(s);
 document.title=s.siteTitle;
 $("#app").innerHTML=`${menu()}<header class="hero" id="home"><div class="hero-media" style="background-image:url('${s.images.hero}')"></div><div class="hero-shade"></div><div class="topbar"><a class="brand" href="#home">${s.siteTitle}</a><button class="hamb" onclick="toggleMenu()" aria-label="Menu"></button></div><div class="hero-copy"><h1>${s.heroTitle}</h1><p>${s.heroSubtitle}</p></div></header>
 <section class="section mustard center"><div class="wrap"><h2 class="statement display">${s.statement}</h2><div class="services">${s.services}</div></div></section>
 <section class="section cream" id="projects"><div class="wrap"><div class="eyebrow">${s.projectsHeading}</div><div class="lead">${s.projectsIntro}</div><div class="bodycopy">${s.projectsBody}</div><div class="projects-grid">${ps.map(p=>`<a class="project-card" href="/?project=${p.slug}" style="background-image:url('${p.cover}')"><div class="label">${p.title}<span class="category">${p.category}</span></div></a>`).join("")}</div></div></section>
 <section class="section cream" id="about"><div class="wrap"><div class="eyebrow">${s.aboutHeading}</div><div class="lead">${s.aboutLead}</div><div class="bodycopy">${s.aboutBody}</div><img class="about-img" src="${s.images.about}" alt=""></div></section>
 <section class="section mustard" id="contact"><div class="wrap"><div class="eyebrow">${s.contactHeading}</div><div class="lead">${s.contactText}</div><div class="contact-links">${s.email?`<a class="pill" href="mailto:${s.email}">Email</a>`:""}${s.instagram?`<a class="pill" href="${s.instagram}">Instagram</a>`:""}${s.linkedin?`<a class="pill" href="${s.linkedin}">LinkedIn</a>`:""}</div><img class="contact-img" src="${s.images.contact}" alt=""></div></section>
 <footer class="footer cream"><div class="wrap footer-row"><div><span class="footer-logo">The Studio</span> &nbsp; by Petra</div><div>${s.copyright}</div></div></footer><a class="cms-note" href="/admin/">Edit website</a>`}
async function project(slug){
 const [s,p]=await Promise.all([getJSON("/content/site.json"),getJSON(`/content/projects/${slug}.json`)]);setTheme(s);document.title=`${p.title} — ${s.siteTitle}`;
 $("#app").innerHTML=`${menu()}<div class="topbar" style="position:relative;left:auto;right:auto;top:auto;padding:4vh 6vw;color:var(--burgundy)"><a class="brand" href="/">${s.siteTitle}</a><button class="hamb" onclick="toggleMenu()"></button></div><main><section class="case-hero cream"><div class="wrap"><a class="back" href="/">← Back to projects</a><h1 class="case-title">${p.title}</h1><div class="lead">${p.intro}</div><img class="case-cover" src="${p.cover}" alt=""></div></section>${p.sections.map((x,i)=>`<section class="case-section ${i%2?"mustard":"cream"}"><div class="wrap"><h2>${x.heading}</h2><div class="bodycopy">${x.text}</div>${x.image?`<img src="${x.image}" alt="">`:""}</div></section>`).join("")}</main><a class="cms-note" href="/admin/">Edit website</a>`}
const q=new URLSearchParams(location.search);q.get("project")?project(q.get("project")):home();